### ISSUE TITLE
Bot doesn't work!

### ISSUE THREAD

**Issue by WaxierCoder** [graynk/Distortioner#11]
![Screenshot_۲۰۲۲-۰۶-۰۲-۱۸-۰۴-۲۱-۹۲۲_org telegram messenger](https://user-images.githubusercontent.com/106753049/171641417-bdf6bd37-d960-4fdd-b919-d77db91c4aac.jpg)

**Comment by graynk** [comment]
Same as #10: The bot is currently down, because I've disabled it. I don't have neither funds, nor the desire to make it scalable and I don't make any money from this. 

I will add appropriate limiters to make it more responsive under load over the next couple of days, then bring it back up. The video processing especially takes a lot of time and it's all running on my own home-server, so if it continues to get overrun with people - expect long waiting times, nothing I can do.
